name: Security Scan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  security_scan:
    name: Security Code Scan
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Security Code Scan
        run: |
          dotnet tool install --global SecurityCodeScan
          SecurityCodeScan --project "../../PACMAN_GAME.sln" --format github
